
import { DJProfile } from './types';

export const CITIES = ["Mumbai", "Delhi", "Bangalore", "Hyderabad", "Chennai", "Kolkata", "Ahmedabad", "Pune", "Jaipur", "Goa"];
export const GENRES = ["Bollywood", "EDM", "Punjabi", "Retro", "House", "Techno", "Hip-Hop"];
export const EVENT_TYPES = ["Wedding", "Corporate", "Club", "College", "Private Party"];


export const MOCK_DJS: DJProfile[] = [
  {
    id: 'dj-rohan-mumbai',
    userId: 'user1',
    name: 'DJ Rohan',
    slug: 'dj-rohan-mumbai',
    city: 'Mumbai',
    genres: ['Bollywood', 'EDM', 'Punjabi'],
    eventTypes: ['Wedding', 'Club', 'Private Party'],
    minFee: 25000,
    bio: 'With over 10 years of experience, DJ Rohan knows how to get the party started. Specializing in high-energy Bollywood and EDM sets for weddings and clubs.',
    instagram: 'https://instagram.com/djrohan',
    youtube: 'https://youtube.com/djrohan',
    soundcloud: 'https://soundcloud.com/djrohan',
    gallery: [
      'https://picsum.photos/seed/rohan1/800/600',
      'https://picsum.photos/seed/rohan2/800/600',
      'https://picsum.photos/seed/rohan3/800/600',
      'https://picsum.photos/seed/rohan4/800/600',
    ],
    videos: [],
    verified: true,
    featured: true,
    avgRating: 4.9,
    profileImage: 'https://picsum.photos/seed/djrohan/400/400',
    coverImage: 'https://picsum.photos/seed/rohan_cover/1600/900',
    reviews: [
      { id: 'r1', authorName: 'Priya S.', authorImage: 'https://picsum.photos/seed/priya/100/100', rating: 5, comment: 'Absolutely amazing! Kept everyone dancing all night at our wedding.', createdAt: new Date('2023-11-15') },
      { id: 'r2', authorName: 'Amit K.', authorImage: 'https://picsum.photos/seed/amit/100/100', rating: 5, comment: 'Professional and played a fantastic set. Highly recommend!', createdAt: new Date('2023-10-20') },
    ],
  },
  {
    id: 'dj-neha-delhi',
    userId: 'user2',
    name: 'DJ Neha',
    slug: 'dj-neha-delhi',
    city: 'Delhi',
    genres: ['Techno', 'House', 'Retro'],
    eventTypes: ['Club', 'Corporate', 'Private Party'],
    minFee: 30000,
    bio: 'Delhi\'s top techno and house DJ. DJ Neha brings an underground vibe to corporate events and exclusive private parties.',
    instagram: 'https://instagram.com/djneha',
    youtube: 'https://youtube.com/djneha',
    soundcloud: 'https://soundcloud.com/djneha',
    gallery: [
      'https://picsum.photos/seed/neha1/800/600',
      'https://picsum.photos/seed/neha2/800/600',
    ],
    videos: [],
    verified: true,
    featured: true,
    avgRating: 4.8,
    profileImage: 'https://picsum.photos/seed/djneha/400/400',
    coverImage: 'https://picsum.photos/seed/neha_cover/1600/900',
    reviews: [
      { id: 'r3', authorName: 'Vikram R.', authorImage: 'https://picsum.photos/seed/vikram/100/100', rating: 5, comment: 'Incredible techno set for our company launch event. Pure class.', createdAt: new Date('2023-12-01') },
    ],
  },
  {
    id: 'dj-sunil-bangalore',
    userId: 'user3',
    name: 'DJ Sunil',
    slug: 'dj-sunil-bangalore',
    city: 'Bangalore',
    genres: ['Hip-Hop', 'Retro', 'Bollywood'],
    eventTypes: ['Private Party', 'College'],
    minFee: 15000,
    bio: 'The king of retro and hip-hop mashups. Perfect for college fests and private parties where you want to vibe.',
    instagram: 'https://instagram.com/djsunil',
    soundcloud: 'https://soundcloud.com/djsunil',
    gallery: [
      'https://picsum.photos/seed/sunil1/800/600',
      'https://picsum.photos/seed/sunil2/800/600',
      'https://picsum.photos/seed/sunil3/800/600',
    ],
    videos: [],
    verified: false,
    featured: false,
    avgRating: 4.5,
    profileImage: 'https://picsum.photos/seed/djsunil/400/400',
    coverImage: 'https://picsum.photos/seed/sunil_cover/1600/900',
    reviews: [
      { id: 'r4', authorName: 'Anjali P.', authorImage: 'https://picsum.photos/seed/anjali/100/100', rating: 4, comment: 'Good music selection for our college fest, but was a bit late.', createdAt: new Date('2023-09-10') },
    ],
  },
    {
    id: 'dj-riya-pune',
    userId: 'user4',
    name: 'DJ Riya',
    slug: 'dj-riya-pune',
    city: 'Pune',
    genres: ['Punjabi', 'Bollywood'],
    eventTypes: ['Wedding', 'Sangeet'],
    minFee: 20000,
    bio: 'Pune\'s favorite wedding DJ! DJ Riya brings the best of Punjabi and Bollywood beats to make your sangeet unforgettable.',
    instagram: 'https://instagram.com/djriya',
    soundcloud: 'https://soundcloud.com/djriya',
    gallery: [
      'https://picsum.photos/seed/riya1/800/600',
      'https://picsum.photos/seed/riya2/800/600'
    ],
    videos: [],
    verified: true,
    featured: false,
    avgRating: 4.7,
    profileImage: 'https://picsum.photos/seed/djriya/400/400',
    coverImage: 'https://picsum.photos/seed/riya_cover/1600/900',
    reviews: [
      { id: 'r5', authorName: 'Karan M.', authorImage: 'https://picsum.photos/seed/karan/100/100', rating: 5, comment: 'DJ Riya was the highlight of our sangeet. Everyone loved her energy!', createdAt: new Date('2023-11-25') },
    ],
  },
  {
    id: 'dj-arjun-goa',
    userId: 'user5',
    name: 'DJ Arjun',
    slug: 'dj-arjun-goa',
    city: 'Goa',
    genres: ['House', 'Techno'],
    eventTypes: ['Club', 'Private Party'],
    minFee: 40000,
    bio: 'Resident DJ at Goa\'s top clubs. Arjun specializes in deep house and melodic techno, perfect for sunset parties.',
    instagram: 'https://instagram.com/djarjun',
    soundcloud: 'https://soundcloud.com/djarjun',
    gallery: [
        'https://picsum.photos/seed/arjun1/800/600',
        'https://picsum.photos/seed/arjun2/800/600',
        'https://picsum.photos/seed/arjun3/800/600'
    ],
    videos: [],
    verified: true,
    featured: true,
    avgRating: 4.9,
    profileImage: 'https://picsum.photos/seed/djarjun/400/400',
    coverImage: 'https://picsum.photos/seed/arjun_cover/1600/900',
    reviews: [
      { id: 'r6', authorName: 'Chloe F.', authorImage: 'https://picsum.photos/seed/chloe/100/100', rating: 5, comment: 'Best sunset set I\'ve ever heard. Pure magic!', createdAt: new Date('2024-01-05') },
    ],
  },
];
