
import { DJProfile, User, Role, Booking, BookingStatus, DJCalendarEntry, CalendarStatus, SubscriptionTier } from './types';

// Expanded Indian Locations
export const INDIAN_LOCATIONS: Record<string, string[]> = {
  "Andhra Pradesh": ["Anantapur", "Chittoor", "East Godavari", "Guntur", "Krishna", "Kurnool", "Prakasam", "Srikakulam", "Sri Potti Sriramulu Nellore", "Visakhapatnam", "Vizianagaram", "West Godavari", "YSR District, Kadapa"],
  "Arunachal Pradesh": ["Tawang", "West Kameng", "East Kameng", "Papum Pare", "Kurung Kumey", "Kra Daadi", "Lower Subansiri", "Upper Subansiri", "West Siang", "East Siang", "Siang", "Upper Siang", "Lower Siang", "Lower Dibang Valley", "Dibang Valley", "Anjaw", "Lohit", "Namsai", "Changlang", "Tirap", "Longding"],
  "Assam": ["Baksa", "Barpeta", "Biswanath", "Bongaigaon", "Cachar", "Charaideo", "Chirang", "Darrang", "Dhemaji", "Dhubri", "Dibrugarh", "Dima Hasao", "Goalpara", "Golaghat", "Hailakandi", "Hojai", "Jorhat", "Kamrup", "Kamrup Metropolitan", "Karbi Anglong", "Karimganj", "Kokrajhar", "Lakhimpur", "Majuli", "Morigaon", "Nagaon", "Nalbari", "Sivasagar", "Sonitpur", "South Salmara-Mankachar", "Tinsukia", "Udalguri", "West Karbi Anglong"],
  "Bihar": ["Araria", "Arwal", "Aurangabad", "Banka", "Begusarai", "Bhagalpur", "Bhojpur", "Buxar", "Darbhanga", "East Champaran", "Gaya", "Gopalganj", "Jamui", "Jehanabad", "Kaimur", "Katihar", "Khagaria", "Kishanganj", "Lakhisarai", "Madhepura", "Madhubani", "Munger", "Muzaffarpur", "Nalanda", "Nawada", "Patna", "Purnia", "Rohtas", "Saharsa", "Samastipur", "Saran", "Sheikhpura", "Sheohar", "Sitamarhi", "Siwan", "Supaul", "Vaishali", "West Champaran"],
  "Chhattisgarh": ["Balod", "Baloda Bazar", "Balrampur", "Bastar", "Bemetara", "Bijapur", "Bilaspur", "Dantewada", "Dhamtari", "Durg", "Gariaband", "Janjgir-Champa", "Jashpur", "Kabirdham", "Kanker", "Kondagaon", "Korba", "Koriya", "Mahasamund", "Mungeli", "Narayanpur", "Raigarh", "Raipur", "Rajnandgaon", "Sukma", "Surajpur", "Surguja"],
  "Goa": ["North Goa", "South Goa"],
  "Gujarat": ["Ahmedabad", "Amreli", "Anand", "Aravalli", "Banaskantha", "Bharuch", "Bhavnagar", "Botad", "Chhota Udaipur", "Dahod", "Dang", "Devbhoomi Dwarka", "Gandhinagar", "Gir Somnath", "Jamnagar", "Junagadh", "Kheda", "Kutch", "Mahisagar", "Mehsana", "Morbi", "Narmada", "Navsari", "Panchmahal", "Patan", "Porbandar", "Rajkot", "Sabarkantha", "Surat", "Surendranagar", "Tapi", "Vadodara", "Valsad"],
  "Haryana": ["Ambala", "Bhiwani", "Charkhi Dadri", "Faridabad", "Fatehabad", "Gurugram", "Hisar", "Jhajjar", "Jind", "Kaithal", "Karnal", "Kurukshetra", "Mahendragarh", "Nuh", "Palwal", "Panchkula", "Panipat", "Rewari", "Rohtak", "Sirsa", "Sonipat", "Yamunanagar"],
  "Himachal Pradesh": ["Bilaspur", "Chamba", "Hamirpur", "Kangra", "Kinnaur", "Kullu", "Lahaul and Spiti", "Mandi", "Shimla", "Sirmaur", "Solan", "Una"],
  "Jharkhand": ["Bokaro", "Chatra", "Deoghar", "Dhanbad", "Dumka", "East Singhbhum", "Garhwa", "Giridih", "Godda", "Gumla", "Hazaribagh", "Jamtara", "Khunti", "Koderma", "Latehar", "Lohardaga", "Pakur", "Palamu", "Ramgarh", "Ranchi", "Sahibganj", "Seraikela Kharsawan", "Simdega", "West Singhbhum"],
  "Karnataka": ["Bagalkot", "Ballari", "Belagavi", "Bengaluru Rural", "Bengaluru Urban", "Bidar", "Chamarajanagar", "Chikkaballapur", "Chikkamagaluru", "Chitradurga", "Dakshina Kannada", "Davangere", "Dharwad", "Gadag", "Hassan", "Haveri", "Kalaburagi", "Kodagu", "Kolar", "Koppal", "Mandya", "Mysuru", "Raichur", "Ramanagara", "Shivamogga", "Tumakuru", "Udupi", "Uttara Kannada", "Vijayapura", "Yadgir"],
  "Kerala": ["Alappuzha", "Ernakulam", "Idukki", "Kannur", "Kasaragod", "Kollam", "Kottayam", "Kozhikode", "Malappuram", "Palakkad", "Pathanamthitta", "Thiruvananthapuram", "Thrissur", "Wayanad"],
  "Madhya Pradesh": ["Agar Malwa", "Alirajpur", "Anuppur", "Ashoknagar", "Balaghat", "Barwani", "Betul", "Bhind", "Bhopal", "Burhanpur", "Chhatarpur", "Chhindwara", "Damoh", "Datia", "Dewas", "Dhar", "Dindori", "Guna", "Gwalior", "Harda", "Hoshangabad", "Indore", "Jabalpur", "Jhabua", "Katni", "Khandwa", "Khargone", "Mandla", "Mandsaur", "Morena", "Narsinghpur", "Neemuch", "Panna", "Raisen", "Rajgarh", "Ratlam", "Rewa", "Sagar", "Satna", "Sehore", "Seoni", "Shahdol", "Shajapur", "Sheopur", "Shivpuri", "Sidhi", "Singrauli", "Tikamgarh", "Ujjain", "Umaria", "Vidisha"],
  "Maharashtra": ["Ahmednagar", "Akola", "Amravati", "Aurangabad", "Beed", "Bhandara", "Buldhana", "Chandrapur", "Dhule", "Gadchiroli", "Gondia", "Hingoli", "Jalgaon", "Jalna", "Kolhapur", "Latur", "Mumbai City", "Mumbai Suburban", "Nagpur", "Nanded", "Nandurbar", "Nashik", "Osmanabad", "Palghar", "Parbhani", "Pune", "Raigad", "Ratnagiri", "Sangli", "Satara", "Sindhudurg", "Solapur", "Thane", "Wardha", "Washim", "Yavatmal"],
  "Manipur": ["Bishnupur", "Chandel", "Churachandpur", "Imphal East", "Imphal West", "Jiribam", "Kakching", "Kamjong", "Kangpokpi", "Noney", "Pherzawl", "Senapati", "Tamenglong", "Tengnoupal", "Thoubal", "Ukhrul"],
  "Meghalaya": ["East Garo Hills", "East Jaintia Hills", "East Khasi Hills", "North Garo Hills", "Ri Bhoi", "South Garo Hills", "South West Garo Hills", "South West Khasi Hills", "West Garo Hills", "West Jaintia Hills", "West Khasi Hills"],
  "Mizoram": ["Aizawl", "Champhai", "Kolasib", "Lawngtlai", "Lunglei", "Mamit", "Saiha", "Serchhip"],
  "Nagaland": ["Dimapur", "Kiphire", "Kohima", "Longleng", "Mokokchung", "Mon", "Peren", "Phek", "Tuensang", "Wokha", "Zunheboto"],
  "Odisha": ["Angul", "Balangir", "Balasore", "Bargarh", "Bhadrak", "Boudh", "Cuttack", "Deogarh", "Dhenkanal", "Gajapati", "Ganjam", "Jagatsinghpur", "Jajpur", "Jharsuguda", "Kalahandi", "Kandhamal", "Kendrapara", "Kendujhar", "Khordha", "Koraput", "Malkangiri", "Mayurbhanj", "Nabarangpur", "Nayagarh", "Nuapada", "Puri", "Rayagada", "Sambalpur", "Subarnapur", "Sundargarh"],
  "Punjab": ["Amritsar", "Barnala", "Bathinda", "Faridkot", "Fatehgarh Sahib", "Fazilka", "Ferozepur", "Gurdaspur", "Hoshiarpur", "Jalandhar", "Kapurthala", "Ludhiana", "Mansa", "Moga", "Mohali", "Muktsar", "Pathankot", "Patiala", "Rupnagar", "Sangrur", "Shaheed Bhagat Singh Nagar", "Tarn Taran"],
  "Rajasthan": ["Ajmer", "Alwar", "Banswara", "Baran", "Barmer", "Bharatpur", "Bhilwara", "Bikaner", "Bundi", "Chittorgarh", "Churu", "Dausa", "Dholpur", "Dungarpur", "Hanumangarh", "Jaipur", "Jaisalmer", "Jalore", "Jhalawar", "Jhunjhunu", "Jodhpur", "Karauli", "Kota", "Nagaur", "Pali", "Pratapgarh", "Rajsamand", "Sawai Madhopur", "Sikar", "Sirohi", "Sri Ganganagar", "Tonk", "Udaipur"],
  "Sikkim": ["East Sikkim", "North Sikkim", "South Sikkim", "West Sikkim"],
  "Tamil Nadu": ["Ariyalur", "Chennai", "Coimbatore", "Cuddalore", "Dharmapuri", "Dindigul", "Erode", "Kanchipuram", "Kanyakumari", "Karur", "Krishnagiri", "Madurai", "Nagapattinam", "Namakkal", "Nilgiris", "Perambalur", "Pudukkottai", "Ramanathapuram", "Salem", "Sivaganga", "Thanjavur", "Theni", "Thoothukudi", "Tiruchirappalli", "Tirunelveli", "Tiruppur", "Tiruvallur", "Tiruvannamalai", "Tiruvarur", "Vellore", "Viluppuram", "Virudhunagar"],
  "Telangana": ["Adilabad", "Bhadradri Kothagudem", "Hyderabad", "Jagtial", "Jangaon", "Jayashankar Bhupalpally", "Jogulamba Gadwal", "Kamareddy", "Karimnagar", "Khammam", "Komaram Bheem", "Mahabubabad", "Mahbubnagar", "Mancherial", "Medak", "Medchal", "Nagarkurnool", "Nalgonda", "Nirmal", "Nizamabad", "Peddapalli", "Rajanna Sircilla", "Rangareddy", "Sangareddy", "Siddipet", "Suryapet", "Vikarabad", "Wanaparthy", "Warangal (Rural)", "Warangal (Urban)", "Yadadri Bhuvanagiri"],
  "Tripura": ["Dhalai", "Gomati", "Khowai", "North Tripura", "Sepahijala", "South Tripura", "Unakoti", "West Tripura"],
  "Uttar Pradesh": ["Agra", "Aligarh", "Allahabad", "Ambedkar Nagar", "Amethi", "Amroha", "Auraiya", "Azamgarh", "Baghpat", "Bahraich", "Ballia", "Balrampur", "Banda", "Barabanki", "Bareilly", "Basti", "Bhadohi", "Bijnor", "Budaun", "Bulandshahr", "Chandauli", "Chitrakoot", "Deoria", "Etah", "Etawah", "Faizabad", "Farrukhabad", "Fatehpur", "Firozabad", "Gautam Buddha Nagar", "Ghaziabad", "Ghazipur", "Gonda", "Gorakhpur", "Hamirpur", "Hapur", "Hardoi", "Hathras", "Jalaun", "Jaunpur", "Jhansi", "Kannauj", "Kanpur Dehat", "Kanpur Nagar", "Kasganj", "Kaushambi", "Kheri", "Kushinagar", "Lalitpur", "Lucknow", "Maharajganj", "Mahoba", "Mainpuri", "Mathura", "Mau", "Meerut", "Mirzapur", "Moradabad", "Muzaffarnagar", "Pilibhit", "Pratapgarh", "Raebareli", "Rampur", "Saharanpur", "Sambhal", "Sant Kabir Nagar", "Shahjahanpur", "Shamli", "Shravasti", "Siddharthnagar", "Sitapur", "Sonbhadra", "Sultanpur", "Unnao", "Varanasi"],
  "Uttarakhand": ["Almora", "Bageshwar", "Chamoli", "Champawat", "Dehradun", "Haridwar", "Nainital", "Pauri Garhwal", "Pithoragarh", "Rudraprayag", "Tehri Garhwal", "Udham Singh Nagar", "Uttarkashi"],
  "West Bengal": ["Alipurduar", "Bankura", "Birbhum", "Cooch Behar", "Dakshin Dinajpur", "Darjeeling", "Hooghly", "Howrah", "Jalpaiguri", "Jhargram", "Kalimpong", "Kolkata", "Malda", "Murshidabad", "Nadia", "North 24 Parganas", "Paschim Bardhaman", "Paschim Medinipur", "Purba Bardhaman", "Purba Medinipur", "Purulia", "South 24 Parganas", "Uttar Dinajpur"]
};

export const GENRES = ["Bollywood", "EDM", "Punjabi", "Retro", "House", "Techno", "Hip-Hop", "Commercial", "Trance", "Rock"];
export const EVENT_TYPES = ["Wedding", "Corporate", "Club", "College", "Private Party", "Sangeet", "Reception", "Pool Party"];


export let MOCK_DJS: DJProfile[] = [
  {
    id: 'dj-1',
    userId: 'user-dj-1',
    name: 'DJ Axle',
    slug: 'dj-axle',
    state: 'Maharashtra',
    city: 'Mumbai City',
    genres: ['Bollywood', 'EDM', 'Punjabi'],
    eventTypes: ['Wedding', 'Club', 'Corporate'],
    minFee: 50000,
    bio: 'High-energy DJ with over 10 years of experience rocking crowds across the country. Specializes in seamless transitions and electrifying Bollywood remixes.',
    gallery: ['https://picsum.photos/seed/dj1_1/800/600', 'https://picsum.photos/seed/dj1_2/800/600', 'https://picsum.photos/seed/dj1_3/800/600', 'https://picsum.photos/seed/dj1_4/800/600'],
    videos: ['https://www.youtube.com/embed/v2aPG3z1a7A'],
    verified: true,
    featured: false,
    avgRating: 4.9,
    reviews: [
      { id: 'rev-1', authorName: 'Priya Sharma', authorImage: 'https://i.pravatar.cc/150?u=priya', rating: 5, comment: 'DJ Axle was absolutely phenomenal at our wedding! The dance floor was packed all night.', createdAt: new Date('2023-10-20') },
      { id: 'rev-2', authorName: 'Rohan Verma', authorImage: 'https://i.pravatar.cc/150?u=rohan', rating: 5, comment: 'Best corporate event DJ we have ever hired. Professional and played the perfect mix.', createdAt: new Date('2023-09-15') },
    ],
    profileImage: 'https://picsum.photos/seed/djaxle/400/400',
    coverImage: 'https://picsum.photos/seed/djaxle_cover/1600/900',
    approvalStatus: 'APPROVED',
    plan: SubscriptionTier.PRO,
    latitude: 19.0760,
    longitude: 72.8777,
  },
   {
    id: 'dj-2',
    userId: 'user-dj-2',
    name: 'DJ Riya',
    slug: 'dj-riya',
    state: 'Karnataka',
    city: 'Bengaluru Urban',
    genres: ['House', 'Techno', 'Retro'],
    eventTypes: ['Club', 'Private Party'],
    minFee: 75000,
    bio: 'Bringing the underground sounds of house and techno to the forefront. Known for deep, groovy sets that keep you dancing till dawn.',
    gallery: ['https://picsum.photos/seed/dj2_1/800/600', 'https://picsum.photos/seed/dj2_2/800/600', 'https://picsum.photos/seed/dj2_3/800/600', 'https://picsum.photos/seed/dj2_4/800/600'],
    videos: [],
    verified: true,
    featured: true,
    avgRating: 5.0,
    reviews: [
        { id: 'rev-3', authorName: 'Anjali Rao', authorImage: 'https://i.pravatar.cc/150?u=anjali', rating: 5, comment: 'Riya knows her music! A true artist. Her techno set was mind-blowing.', createdAt: new Date('2023-11-01') },
    ],
    profileImage: 'https://picsum.photos/seed/djriya/400/400',
    coverImage: 'https://picsum.photos/seed/djriya_cover/1600/900',
    approvalStatus: 'APPROVED',
    plan: SubscriptionTier.ELITE,
    latitude: 12.9716,
    longitude: 77.5946,
  },
  {
    id: 'dj-3',
    userId: 'user-dj-3',
    name: 'DJ Spinz',
    slug: 'dj-spinz',
    state: 'Delhi',
    city: 'South Delhi',
    genres: [],
    eventTypes: [],
    minFee: 20000,
    bio: 'Upcoming DJ specializing in Hip-Hop and commercial mixes. Ready to bring the vibes to your college fest or private party.',
    gallery: ['https://picsum.photos/seed/dj3_1/800/600', 'https://picsum.photos/seed/dj3_2/800/600'],
    videos: [],
    verified: false,
    featured: false,
    avgRating: 0,
    reviews: [],
    profileImage: 'https://picsum.photos/seed/djspinz/400/400',
    coverImage: 'https://picsum.photos/seed/djspinz_cover/1600/900',
    approvalStatus: 'PENDING',
    plan: SubscriptionTier.FREE,
    latitude: 28.7041,
    longitude: 77.1025,
  },
  {
    id: 'dj-4',
    userId: 'user-dj-4',
    name: 'DJ Venom',
    slug: 'dj-venom',
    state: 'Gujarat',
    city: 'Ahmedabad',
    genres: ['Bollywood', 'Commercial'],
    eventTypes: ['Wedding', 'Sangeet'],
    minFee: 35000,
    bio: 'Ahmedabad\'s favorite for weddings. I make sure the baraat never stops dancing.',
    gallery: ['https://picsum.photos/seed/dj4_1/800/600'],
    videos: [],
    verified: true,
    featured: true,
    avgRating: 4.8,
    reviews: [
         { id: 'rev-4', authorName: 'Karan Patel', authorImage: 'https://i.pravatar.cc/150?u=karan', rating: 5, comment: 'Best DJ in Ahmedabad for weddings!', createdAt: new Date('2023-12-01') },
    ],
    profileImage: 'https://picsum.photos/seed/djvenom/400/400',
    coverImage: 'https://picsum.photos/seed/djvenom_cover/1600/900',
    approvalStatus: 'APPROVED',
    plan: SubscriptionTier.PRO,
    latitude: 23.0225,
    longitude: 72.5714,
  },
  {
    id: 'dj-5',
    userId: 'user-dj-5',
    name: 'DJ Bliss',
    slug: 'dj-bliss',
    state: 'Gujarat',
    city: 'Ahmedabad',
    genres: ['EDM', 'House'],
    eventTypes: ['Club', 'Party'],
    minFee: 25000,
    bio: 'Club specialist in Ahmedabad.',
    gallery: ['https://picsum.photos/seed/dj5_1/800/600'],
    videos: [],
    verified: false,
    featured: false,
    avgRating: 4.5,
    reviews: [
        { id: 'rev-5', authorName: 'Sneha', authorImage: 'https://i.pravatar.cc/150?u=sneha', rating: 4, comment: 'Great vibe.', createdAt: new Date('2023-11-10') }
    ],
    profileImage: 'https://picsum.photos/seed/djbliss/400/400',
    coverImage: 'https://picsum.photos/seed/djbliss_cover/1600/900',
    approvalStatus: 'APPROVED',
    plan: SubscriptionTier.FREE,
    latitude: 23.0225,
    longitude: 72.5714,
  }
];

export let MOCK_USERS: User[] = [
    { id: 'user-admin', name: 'Admin', email: 'admin@djbook.in', password: 'Ajaydjbook@909911', role: Role.ADMIN },
    { id: 'user-customer', name: 'Aarav Mehta', email: 'customer@email.com', password: 'password', role: Role.CUSTOMER },
    { id: 'user-dj-1', name: 'DJ Axle', email: 'axle@email.com', password: 'password', role: Role.DJ, djProfileId: 'dj-1' },
    { id: 'user-dj-2', name: 'DJ Riya', email: 'riya@email.com', password: 'password', role: Role.DJ, djProfileId: 'dj-2' },
    { id: 'user-dj-3', name: 'DJ Spinz', email: 'spinz@email.com', password: 'password', role: Role.DJ, djProfileId: 'dj-3' },
    { id: 'user-dj-4', name: 'DJ Venom', email: 'venom@email.com', password: 'password', role: Role.DJ, djProfileId: 'dj-4' },
    { id: 'user-dj-5', name: 'DJ Bliss', email: 'bliss@email.com', password: 'password', role: Role.DJ, djProfileId: 'dj-5' },
];

export let MOCK_BOOKINGS: Booking[] = [
   {
        id: 'booking-1',
        djId: 'dj-1',
        djName: 'DJ Axle',
        djProfileImage: 'https://picsum.photos/seed/djaxle/400/400',
        customerId: 'user-customer',
        customerName: 'Aarav Mehta',
        eventDate: new Date('2024-07-15'),
        eventType: 'Wedding',
        location: 'Mumbai',
        status: BookingStatus.ACCEPTED,
        notes: 'Need a good mix of old and new Bollywood hits.'
    },
    {
        id: 'booking-2',
        djId: 'dj-2',
        djName: 'DJ Riya',
        djProfileImage: 'https://picsum.photos/seed/djriya/400/400',
        customerId: 'user-customer',
        customerName: 'Aarav Mehta',
        eventDate: new Date('2024-05-20'),
        eventType: 'Club',
        location: 'Bangalore',
        status: BookingStatus.COMPLETED,
        notes: 'Strictly techno.'
    },
     {
        id: 'booking-3',
        djId: 'dj-1',
        djName: 'DJ Axle',
        djProfileImage: 'https://picsum.photos/seed/djaxle/400/400',
        customerId: 'user-customer',
        customerName: 'Aarav Mehta',
        eventDate: new Date('2024-08-01'),
        eventType: 'Corporate',
        location: 'Pune',
        status: BookingStatus.PENDING,
        notes: 'Corporate event for our annual gala.'
    },
    {
        id: 'booking-4',
        djId: 'dj-2',
        djName: 'DJ Riya',
        djProfileImage: 'https://picsum.photos/seed/djriya/400/400',
        customerId: 'user-customer',
        customerName: 'Aarav Mehta',
        eventDate: new Date('2024-06-10'),
        eventType: 'Private Party',
        location: 'Goa',
        status: BookingStatus.REJECTED,
        notes: 'Birthday party inquiry.'
    }
];

export let MOCK_CALENDAR_ENTRIES: DJCalendarEntry[] = [
    {
        id: 'cal-1',
        djProfileId: 'dj-1',
        date: new Date('2024-07-15'),
        status: CalendarStatus.BOOKED,
        title: 'Platform: Wedding',
        bookingId: 'booking-1',
    },
    {
        id: 'cal-2',
        djProfileId: 'dj-1',
        date: new Date('2024-08-01'),
        status: CalendarStatus.HOLD,
        title: 'Platform Inquiry',
        bookingId: 'booking-3',
    },
    {
        id: 'cal-3',
        djProfileId: 'dj-2',
        date: new Date('2024-07-20'),
        status: CalendarStatus.UNAVAILABLE,
        title: 'Day Off',
    }
];
